#!/usr/bin/env python3
"""Run exact DMD and gDMD for the confined-cylinder dataset."""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = REPO_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from gdmd import GDMDAnalysisOptions, compute_dns_gap_fields, rectangular_window_mask, restrict_state_matrix, run_gdmd_analysis  # noqa: E402


@dataclass
class Config:
    input_file: Path
    output_file: Path = Path("results/cylinder2d_gdmd_results.npz")
    n_modes: int = 10
    n_neighbors: int = 15
    dt: float = 1.0 / 1600.0
    xlim: tuple[float, float] = (0.3, 1.5)
    ylim: tuple[float, float] = (0.05, 0.35)
    first_snapshot: int = 0
    last_snapshot: int | None = None
    nproc: int = max(1, (os.cpu_count() or 2) - 1)
    ray_address: str | None = None
    gap_weights: str = "inv_r"
    use_tke_weighting: bool = False
    tke_weight_alpha: float = 0.5
    tke_weight_floor: float = 0.05
    save_figures: Path | None = None
    show: bool = False
    mode_to_plot: int = 4
    component_to_plot: int = 0


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", dest="input_file", type=Path, required=True, help="Input .npz generated by run_cylinder2d_dns.py.")
    parser.add_argument("--output", dest="output_file", type=Path, default=Config.output_file)
    parser.add_argument("--n-modes", type=int, default=Config.n_modes)
    parser.add_argument("--n-neighbors", type=int, default=Config.n_neighbors)
    parser.add_argument("--dt", type=float, default=Config.dt, help="Internal delay between the two images of a stored pair.")
    parser.add_argument("--xlim", type=float, nargs=2, default=Config.xlim)
    parser.add_argument("--ylim", type=float, nargs=2, default=Config.ylim)
    parser.add_argument("--first-snapshot", type=int, default=Config.first_snapshot)
    parser.add_argument("--last-snapshot", type=int, default=Config.last_snapshot)
    parser.add_argument("--nproc", type=int, default=Config.nproc, help="Ray workers; use 1 for serial execution.")
    parser.add_argument("--ray-address", type=str, default=Config.ray_address)
    parser.add_argument("--gap-weights", choices=("uniform", "inv_r", "gaussian"), default=Config.gap_weights)
    parser.add_argument("--use-tke-weighting", action=argparse.BooleanOptionalAction, default=Config.use_tke_weighting)
    parser.add_argument("--tke-weight-alpha", type=float, default=Config.tke_weight_alpha)
    parser.add_argument("--tke-weight-floor", type=float, default=Config.tke_weight_floor)
    parser.add_argument("--save-figures", type=Path, default=Config.save_figures)
    parser.add_argument("--show", action=argparse.BooleanOptionalAction, default=Config.show)
    parser.add_argument("--mode-to-plot", type=int, default=Config.mode_to_plot, help="One-based matched-mode index for the optional mode figure.")
    parser.add_argument("--component-to-plot", type=int, choices=(0, 1), default=Config.component_to_plot)
    return parser


def config_from_args(args: argparse.Namespace) -> Config:
    values = vars(args).copy()
    values["xlim"] = tuple(values["xlim"])
    values["ylim"] = tuple(values["ylim"])
    return Config(**values)


def load_dataset(path: Path) -> dict[str, np.ndarray]:
    if not path.exists():
        raise FileNotFoundError(path)
    with np.load(path, allow_pickle=False) as data:
        required = {"vel1", "vel2", "seeds1", "seeds2", "xglobal", "centers", "R"}
        missing = sorted(required.difference(data.files))
        if missing:
            raise KeyError(f"Missing arrays in {path}: {missing}")
        return {name: data[name] for name in data.files}


def run_case(cfg: Config) -> dict[str, np.ndarray]:
    data = load_dataset(cfg.input_file)
    print(f"Loaded {cfg.input_file}")
    print(f"Stored snapshot pairs: {data['vel1'].shape[2]}")

    density1, density2 = compute_dns_gap_fields(
        data["seeds1"],
        data["seeds2"],
        data["xglobal"],
        n_neighbors=cfg.n_neighbors,
        gap_weights=cfg.gap_weights,
        nproc=cfg.nproc,
        ray_address=cfg.ray_address,
    )

    point_mask = rectangular_window_mask(
        data["xglobal"],
        cfg.xlim,
        cfg.ylim,
        centers=data["centers"],
        radius=float(data["R"]),
    )
    xdmd = data["xglobal"][point_mask]
    n_points = xdmd.shape[0]
    if n_points == 0:
        raise RuntimeError("The DMD window contains no grid points.")

    exact1 = restrict_state_matrix(data["vel1"], point_mask)
    exact2 = restrict_state_matrix(data["vel2"], point_mask)
    gap1 = restrict_state_matrix(density1, point_mask)
    gap2 = restrict_state_matrix(density2, point_mask)

    last = cfg.last_snapshot if cfg.last_snapshot is not None else exact1.shape[1]
    indices = np.arange(cfg.first_snapshot, last)
    if indices.size < cfg.n_modes + 1:
        raise RuntimeError("The selected snapshot range is too short for the requested number of modes.")

    options = GDMDAnalysisOptions(
        n_modes=cfg.n_modes,
        dt_exact=cfg.dt,
        dt_gap=cfg.dt,
        use_tke_weighting=cfg.use_tke_weighting,
        tke_weight_alpha=cfg.tke_weight_alpha,
        tke_weight_floor=cfg.tke_weight_floor,
        match_w_eig=0.4,
        match_w_mode=0.6,
        weighted_match_w_eig=0.1,
        weighted_match_w_mode=0.8,
    )
    results = run_gdmd_analysis(
        exact1=exact1,
        exact2=exact2,
        gap1=gap1,
        gap2=gap2,
        n_points=n_points,
        options=options,
        exact_indices=indices,
        gap_indices=indices,
    )
    results.update(
        {
            "xdmd": xdmd,
            "point_mask": point_mask,
            "xglobal": data["xglobal"],
            "trange_exact": indices,
            "trange_gap": indices,
            "xlim": np.asarray(cfg.xlim),
            "ylim": np.asarray(cfg.ylim),
            "case": np.asarray("cylinder2d"),
        }
    )
    return results


def save_results(results: dict[str, np.ndarray], output_file: Path) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(output_file, **results)
    print(f"Saved {output_file}")


def save_or_show_figures(results: dict[str, np.ndarray], cfg: Config) -> None:
    if cfg.save_figures is None and not cfg.show:
        return
    import matplotlib.pyplot as plt

    if cfg.save_figures is not None:
        cfg.save_figures.mkdir(parents=True, exist_ok=True)

    eig_key = "E_gdmd_weighted" if cfg.use_tke_weighting else "E_gdmd"
    mode_key = "Phi_gdmd_weighted" if cfg.use_tke_weighting else "Phi_gdmd"
    label = "TKE-weighted gDMD" if cfg.use_tke_weighting else "gDMD"

    fig, ax = plt.subplots(figsize=(4.5, 4.0))
    ax.plot(np.real(results["E_exact"]), np.imag(results["E_exact"]), "s", mfc="none", label="Exact DMD")
    ax.plot(np.real(results[eig_key]), np.imag(results[eig_key]), "^", mfc="none", label=label)
    ax.set_aspect("equal", adjustable="box")
    ax.set_xlabel(r"$\mathrm{Re}(\lambda)$")
    ax.set_ylabel(r"$\mathrm{Im}(\lambda)$")
    ax.legend(frameon=False)
    fig.tight_layout()
    if cfg.save_figures is not None:
        fig.savefig(cfg.save_figures / "cylinder2d_eigenvalues.png", dpi=300)

    k = cfg.mode_to_plot - 1
    if k < 0 or k >= results[mode_key].shape[1]:
        raise ValueError("--mode-to-plot is out of range for the matched modes.")
    component = cfg.component_to_plot
    n_points = results["xdmd"].shape[0]
    phi_exact = np.real(results["Phi_exact_matched"][:, k].reshape(n_points, 2)[:, component])
    phi_gdmd = np.real(results[mode_key][:, k].reshape(n_points, 2)[:, component])

    fig2, axes = plt.subplots(2, 1, figsize=(6.0, 4.5), sharex=True, sharey=True)
    for ax_i, field, title in zip(axes, (phi_exact, phi_gdmd), ("Exact DMD", label), strict=False):
        im = ax_i.tripcolor(results["xdmd"][:, 0], results["xdmd"][:, 1], field, shading="gouraud")
        ax_i.set_xlim(results["xlim"])
        ax_i.set_ylim(results["ylim"])
        ax_i.set_aspect("equal", adjustable="box")
        ax_i.set_title(title)
        fig2.colorbar(im, ax=ax_i)
    fig2.tight_layout()
    if cfg.save_figures is not None:
        fig2.savefig(cfg.save_figures / "cylinder2d_mode_comparison.png", dpi=300)

    if cfg.use_tke_weighting:
        fig3, ax3 = plt.subplots(figsize=(5.0, 2.5))
        im3 = ax3.tripcolor(results["xdmd"][:, 0], results["xdmd"][:, 1], results["tke_weight"], shading="gouraud")
        ax3.set_xlim(results["xlim"])
        ax3.set_ylim(results["ylim"])
        ax3.set_aspect("equal", adjustable="box")
        ax3.set_title("TKE-based gDMD weight")
        fig3.colorbar(im3, ax=ax3)
        fig3.tight_layout()
        if cfg.save_figures is not None:
            fig3.savefig(cfg.save_figures / "cylinder2d_tke_weight.png", dpi=300)

    if cfg.show:
        plt.show()
    else:
        plt.close("all")


def main() -> None:
    cfg = config_from_args(build_arg_parser().parse_args())
    results = run_case(cfg)
    save_results(results, cfg.output_file)
    save_or_show_figures(results, cfg)


if __name__ == "__main__":
    main()
